name: MultiVersionPM4
api: 4.5.2
main: skyss0fly\MultiVersionPM4\Loader
version: 0.486.1
description: A plugin to allows older Minecraft client versions to connect to newer server versions.
mcpe-protocol: 527
author: skyss0fly
permissions:
  multiversion.command:
    default: op
